server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
