apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: comtudux/api-gateway-mise:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 10909
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: ISSUER_URI
            valueFrom:
              configMapKeyRef:
                name: issuer-uri-cm
                key: issuer_uri
          - name: AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: audience-cm
                key: audience
          - name: CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: client-id-cm
                key: client_id                                                                  
          - name: CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                name: client-secret-cm
                key: client_secret      

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
  - port: 80
    targetPort: 10909           
              
