apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: comtudux/order-mise:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 10002
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-cm
                key: config_url
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-cm
                key: hostname
          - name: ISSUER_URI
            valueFrom:
              configMapKeyRef:
                name: issuer-uri-cm
                key: issuer_uri
          - name: AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: audience-cm
                key: audience
          - name: CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: client-id-cm
                key: client_id                                                                  
          - name: CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                name: client-secret-cm
                key: client_secret                                          

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - port: 80
    targetPort: 10002
        
