version: '3'

services:
    db-product:
        image: mysql
        container_name: micro-productdb
        ports:
            - "3306:3306"
        command: --init-file /sql/init.sql
        volumes:
            - ./sql/init.sql:/sql/init.sql            
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
    redis:
        image: redis:latest
        container_name: redis
        ports:
        - "6379:6379"
        volumes:
        - redis_data:/data            
          
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin-micro-test
        ports:
        - "9411:9411"

volumes:
  redis_data:                      