apiVersion: v1
kind: Service
metadata:
  namespace: my-namespace2
  name: service-registry-app
spec:
  type: NodePort
  selector:
    app: service-registry-app
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30087
